import { isValidShareSlug } from "@/lib/preview/share-slug";
import {
  normalizeShareChannel,
  type ShareChannel,
} from "@/lib/analytics/channel";

export const ORIGIN_KINDS = [
  "direct",
  "organic",
  "utm",
  "share",
] as const;

export type OriginKind = (typeof ORIGIN_KINDS)[number];

export type OriginSnapshot = {
  kind: OriginKind;
  shareSlug: string | null;
  shareChannel: ShareChannel | null;
  referrerHost: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  at: number;
};

export type ShareAttribution = {
  shareSlug: string;
  shareChannel: ShareChannel | null;
  at: number;
};

export type AcquisitionState = {
  origin: OriginSnapshot;
  share: ShareAttribution | null;
};

type IncomingTouch =
  | {
      type: "share";
      shareSlug: string;
      shareChannel: ShareChannel | null;
      at: number;
    }
  | {
      type: "utm";
      utmSource: string;
      utmMedium: string | null;
      utmCampaign: string | null;
      referrerHost: string | null;
      at: number;
    }
  | {
      type: "organic";
      referrerHost: string;
      at: number;
    }
  | {
      type: "direct";
      at: number;
    };

const MAX_UTM_LENGTH = 64;
const METAPROM_HOST_RE = /(^|\.)metaprom\.com$/i;

/**
 * Attribution rule (deterministic, first-touch):
 *
 * 1. Original origin is written once in the 30-day window:
 *    share > utm > organic external referrer > direct.
 *    Internal Metaprom navigation never overwrites it.
 * 2. Share attribution is the first public Share opened in that window.
 *    Later Shares and internal routes do not replace it.
 * 3. "Where did this user originally come from?" → origin.kind (+ utm/share).
 * 4. "Was this signup generated by a Metaprom Share?" → share != null.
 */
export function resolveAcquisitionState(
  existing: AcquisitionState | null,
  incoming: IncomingTouch | null,
): AcquisitionState | null {
  if (!incoming) {
    return existing;
  }

  if (!existing) {
    return stateFromIncoming(incoming);
  }

  const next: AcquisitionState = {
    origin: existing.origin,
    share: existing.share,
  };

  if (!next.share && incoming.type === "share") {
    next.share = {
      shareSlug: incoming.shareSlug,
      shareChannel: incoming.shareChannel,
      at: incoming.at,
    };
  }

  return next;
}

function stateFromIncoming(incoming: IncomingTouch): AcquisitionState {
  if (incoming.type === "share") {
    const share: ShareAttribution = {
      shareSlug: incoming.shareSlug,
      shareChannel: incoming.shareChannel,
      at: incoming.at,
    };
    return {
      origin: {
        kind: "share",
        shareSlug: incoming.shareSlug,
        shareChannel: incoming.shareChannel,
        referrerHost: null,
        utmSource: null,
        utmMedium: null,
        utmCampaign: null,
        at: incoming.at,
      },
      share,
    };
  }

  if (incoming.type === "utm") {
    return {
      origin: {
        kind: "utm",
        shareSlug: null,
        shareChannel: null,
        referrerHost: incoming.referrerHost,
        utmSource: incoming.utmSource,
        utmMedium: incoming.utmMedium,
        utmCampaign: incoming.utmCampaign,
        at: incoming.at,
      },
      share: null,
    };
  }

  if (incoming.type === "organic") {
    return {
      origin: {
        kind: "organic",
        shareSlug: null,
        shareChannel: null,
        referrerHost: incoming.referrerHost,
        utmSource: null,
        utmMedium: null,
        utmCampaign: null,
        at: incoming.at,
      },
      share: null,
    };
  }

  return {
    origin: {
      kind: "direct",
      shareSlug: null,
      shareChannel: null,
      referrerHost: null,
      utmSource: null,
      utmMedium: null,
      utmCampaign: null,
      at: incoming.at,
    },
    share: null,
  };
}

export function classifyReferrerHost(
  referrer: string | null,
  requestHost: string,
): string | null {
  if (!referrer) {
    return null;
  }

  try {
    const url = new URL(referrer);
    const host = url.hostname.replace(/^www\./i, "").toLowerCase();
    const current = requestHost.replace(/^www\./i, "").toLowerCase();
    if (!host || host === current || METAPROM_HOST_RE.test(host)) {
      return null;
    }
    return host.slice(0, MAX_UTM_LENGTH);
  } catch {
    return null;
  }
}

export function sanitizeUtmValue(value: unknown): string | null {
  if (typeof value !== "string") {
    return null;
  }
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > MAX_UTM_LENGTH) {
    return null;
  }
  if (/[&=<>]/.test(trimmed) || trimmed.includes("@")) {
    return null;
  }
  return trimmed;
}

export function incomingShareTouch(input: {
  shareSlug: string;
  shareChannel: ShareChannel | null;
  at?: number;
}): IncomingTouch | null {
  if (!isValidShareSlug(input.shareSlug)) {
    return null;
  }
  return {
    type: "share",
    shareSlug: input.shareSlug,
    shareChannel: input.shareChannel,
    at: input.at ?? Date.now(),
  };
}

export function incomingFromSearchParams(input: {
  searchParams: { get(name: string): string | null };
  referrer: string | null;
  requestHost: string;
  pathname: string;
  at?: number;
}): IncomingTouch | null {
  const at = input.at ?? Date.now();
  const utmSource = sanitizeUtmValue(input.searchParams.get("utm_source"));
  if (utmSource) {
    return {
      type: "utm",
      utmSource,
      utmMedium: sanitizeUtmValue(input.searchParams.get("utm_medium")),
      utmCampaign: sanitizeUtmValue(input.searchParams.get("utm_campaign")),
      referrerHost: classifyReferrerHost(input.referrer, input.requestHost),
      at,
    };
  }

  if (input.pathname === "/") {
    const referrerHost = classifyReferrerHost(input.referrer, input.requestHost);
    if (referrerHost) {
      return { type: "organic", referrerHost, at };
    }
    return { type: "direct", at };
  }

  return null;
}

type CookieOrigin = {
  k: OriginKind;
  s?: string;
  c?: string;
  rh?: string;
  us?: string;
  um?: string;
  uc?: string;
  t: number;
};

type CookieShare = {
  s: string;
  c?: string;
  t: number;
};

type CookiePayload = {
  o: CookieOrigin;
  sh?: CookieShare;
};

export function serializeAcquisitionState(state: AcquisitionState): string {
  const payload: CookiePayload = {
    o: {
      k: state.origin.kind,
      t: state.origin.at,
      ...(state.origin.shareSlug ? { s: state.origin.shareSlug } : {}),
      ...(state.origin.shareChannel ? { c: state.origin.shareChannel } : {}),
      ...(state.origin.referrerHost ? { rh: state.origin.referrerHost } : {}),
      ...(state.origin.utmSource ? { us: state.origin.utmSource } : {}),
      ...(state.origin.utmMedium ? { um: state.origin.utmMedium } : {}),
      ...(state.origin.utmCampaign ? { uc: state.origin.utmCampaign } : {}),
    },
  };

  if (state.share) {
    payload.sh = {
      s: state.share.shareSlug,
      t: state.share.at,
      ...(state.share.shareChannel ? { c: state.share.shareChannel } : {}),
    };
  }

  return JSON.stringify(payload);
}

export function parseAcquisitionState(raw: string | null | undefined): AcquisitionState | null {
  if (!raw) {
    return null;
  }

  try {
    const payload = JSON.parse(raw) as CookiePayload;
    if (!payload || typeof payload !== "object" || !payload.o) {
      return null;
    }

    const kind = ORIGIN_KINDS.includes(payload.o.k) ? payload.o.k : null;
    if (!kind || typeof payload.o.t !== "number") {
      return null;
    }

    const originShareSlug =
      typeof payload.o.s === "string" && isValidShareSlug(payload.o.s)
        ? payload.o.s
        : null;
    const originChannel = normalizeShareChannel(payload.o.c);

    const origin: OriginSnapshot = {
      kind,
      shareSlug: originShareSlug,
      shareChannel: originChannel,
      referrerHost:
        typeof payload.o.rh === "string" ? payload.o.rh.slice(0, MAX_UTM_LENGTH) : null,
      utmSource:
        typeof payload.o.us === "string" ? payload.o.us.slice(0, MAX_UTM_LENGTH) : null,
      utmMedium:
        typeof payload.o.um === "string" ? payload.o.um.slice(0, MAX_UTM_LENGTH) : null,
      utmCampaign:
        typeof payload.o.uc === "string" ? payload.o.uc.slice(0, MAX_UTM_LENGTH) : null,
      at: payload.o.t,
    };

    let share: ShareAttribution | null = null;
    if (payload.sh && isValidShareSlug(payload.sh.s) && typeof payload.sh.t === "number") {
      share = {
        shareSlug: payload.sh.s,
        shareChannel: normalizeShareChannel(payload.sh.c),
        at: payload.sh.t,
      };
    }

    return { origin, share };
  } catch {
    return null;
  }
}

export function isShareAttributed(state: AcquisitionState | null): boolean {
  return Boolean(state?.share?.shareSlug);
}
