-- Stripe V1 packages: prepaid commercial / advertising-asset balances.
-- Non-destructive: nullable asset_id on purchases + new balance/ledger tables.

-- Package purchases from /planes are not bound to a single asset.
alter table public.purchases
  alter column asset_id drop not null;

create table if not exists public.entitlement_balances (
  user_id uuid primary key references auth.users(id) on delete cascade,
  commercials_remaining integer not null default 0
    check (commercials_remaining >= 0),
  advertising_assets_remaining integer not null default 0
    check (advertising_assets_remaining >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.entitlement_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_type text not null,
  entitlement_kind text not null,
  quantity integer not null,
  balance_after integer not null,
  purchase_id bigint references public.purchases(id) on delete set null,
  asset_id bigint references public.assets(id) on delete set null,
  product_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint entitlement_ledger_entry_type_check check (
    entry_type in ('grant', 'consume', 'adjust')
  ),
  constraint entitlement_ledger_kind_check check (
    entitlement_kind in ('commercial', 'advertising_asset')
  ),
  constraint entitlement_ledger_quantity_check check (quantity <> 0),
  constraint entitlement_ledger_metadata_object_check check (
    jsonb_typeof(metadata) = 'object'
  )
);

-- Webhook retries must not grant the same package purchase twice.
create unique index if not exists entitlement_ledger_purchase_grant_uidx
  on public.entitlement_ledger(purchase_id)
  where entry_type = 'grant' and purchase_id is not null;

create index if not exists entitlement_ledger_user_id_idx
  on public.entitlement_ledger(user_id);

create index if not exists entitlement_ledger_created_at_idx
  on public.entitlement_ledger(created_at desc);

create or replace function public.set_entitlement_balances_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_entitlement_balances_updated_at
  on public.entitlement_balances;
create trigger set_entitlement_balances_updated_at
  before update on public.entitlement_balances
  for each row
  execute function public.set_entitlement_balances_updated_at();

/**
 * Grant package quantity once per completed purchase (idempotent).
 * Returns true when a new grant was applied; false when already granted.
 */
create or replace function public.grant_package_entitlement(
  p_user_id uuid,
  p_purchase_id bigint,
  p_product_id text,
  p_entitlement_kind text,
  p_quantity integer,
  p_metadata jsonb default '{}'::jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'grant quantity must be positive';
  end if;

  if p_entitlement_kind not in ('commercial', 'advertising_asset') then
    raise exception 'invalid entitlement kind: %', p_entitlement_kind;
  end if;

  insert into public.entitlement_balances (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  begin
    if p_entitlement_kind = 'commercial' then
      update public.entitlement_balances
      set commercials_remaining = commercials_remaining + p_quantity
      where user_id = p_user_id
      returning commercials_remaining into v_balance;
    else
      update public.entitlement_balances
      set advertising_assets_remaining = advertising_assets_remaining + p_quantity
      where user_id = p_user_id
      returning advertising_assets_remaining into v_balance;
    end if;

    insert into public.entitlement_ledger (
      user_id,
      entry_type,
      entitlement_kind,
      quantity,
      balance_after,
      purchase_id,
      product_id,
      metadata
    ) values (
      p_user_id,
      'grant',
      p_entitlement_kind,
      p_quantity,
      v_balance,
      p_purchase_id,
      p_product_id,
      coalesce(p_metadata, '{}'::jsonb)
    );

    return true;
  exception
    when unique_violation then
      return false;
  end;
end;
$$;

/**
 * Atomically consume one entitlement unit for the authenticated owner.
 * Raises when balance is insufficient.
 */
create or replace function public.consume_entitlement(
  p_user_id uuid,
  p_entitlement_kind text,
  p_quantity integer default 1,
  p_asset_id bigint default null,
  p_product_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'consume quantity must be positive';
  end if;

  insert into public.entitlement_balances (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  if p_entitlement_kind = 'commercial' then
    update public.entitlement_balances
    set commercials_remaining = commercials_remaining - p_quantity
    where user_id = p_user_id
      and commercials_remaining >= p_quantity
    returning commercials_remaining into v_balance;
  elsif p_entitlement_kind = 'advertising_asset' then
    update public.entitlement_balances
    set advertising_assets_remaining = advertising_assets_remaining - p_quantity
    where user_id = p_user_id
      and advertising_assets_remaining >= p_quantity
    returning advertising_assets_remaining into v_balance;
  else
    raise exception 'invalid entitlement kind: %', p_entitlement_kind;
  end if;

  if v_balance is null then
    raise exception 'insufficient % entitlement balance', p_entitlement_kind
      using errcode = 'P0001';
  end if;

  insert into public.entitlement_ledger (
    user_id,
    entry_type,
    entitlement_kind,
    quantity,
    balance_after,
    asset_id,
    product_id,
    metadata
  ) values (
    p_user_id,
    'consume',
    p_entitlement_kind,
    -p_quantity,
    v_balance,
    p_asset_id,
    p_product_id,
    coalesce(p_metadata, '{}'::jsonb)
  );

  return v_balance;
end;
$$;

revoke all on function public.grant_package_entitlement(uuid, bigint, text, text, integer, jsonb)
  from public, anon, authenticated;
grant execute on function public.grant_package_entitlement(uuid, bigint, text, text, integer, jsonb)
  to service_role;

revoke all on function public.consume_entitlement(uuid, text, integer, bigint, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.consume_entitlement(uuid, text, integer, bigint, text, jsonb)
  to service_role;

alter table public.entitlement_balances enable row level security;
alter table public.entitlement_ledger enable row level security;

drop policy if exists "entitlement_balances_select_own" on public.entitlement_balances;
create policy "entitlement_balances_select_own"
  on public.entitlement_balances
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "entitlement_ledger_select_own" on public.entitlement_ledger;
create policy "entitlement_ledger_select_own"
  on public.entitlement_ledger
  for select
  to authenticated
  using (user_id = auth.uid());

grant select on table public.entitlement_balances to authenticated;
grant select on table public.entitlement_ledger to authenticated;
grant all on table public.entitlement_balances to service_role;
grant all on table public.entitlement_ledger to service_role;

do $$
declare
  ledger_id_sequence regclass;
begin
  ledger_id_sequence := pg_get_serial_sequence('public.entitlement_ledger', 'id')::regclass;
  if ledger_id_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', ledger_id_sequence);
  end if;
end;
$$;

notify pgrst, 'reload schema';
