-- Phase 1 memberships: persist Stripe subscription identity.
-- Additive only. Does not alter purchases, entitlement balances, or
-- historical payment rows. Credit grants still use grant_package_entitlement
-- (one ledger grant per invoice-keyed purchase row).

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Canonical key: golden_monthly | golden_annual | premium_monthly | premium_annual
  membership_key text not null,
  tier text not null,
  billing_cycle text not null,
  stripe_customer_id text not null,
  stripe_subscription_id text not null,
  stripe_price_id text not null,
  -- Stripe subscription.status, not a Metaprom grace-period policy.
  status text not null,
  current_period_end timestamptz,
  last_invoice_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint memberships_tier_check check (tier in ('golden', 'premium')),
  constraint memberships_billing_cycle_check check (
    billing_cycle in ('monthly', 'annual')
  ),
  constraint memberships_membership_key_check check (
    membership_key in (
      'golden_monthly',
      'golden_annual',
      'premium_monthly',
      'premium_annual'
    )
  )
);

comment on table public.memberships is
  'Phase 1 Stripe subscription identity. Credits are granted per paid invoice, never reset.';

comment on column public.memberships.user_id is
  'Authenticated Metaprom user who started checkout. Never taken from client body.';

comment on column public.memberships.stripe_subscription_id is
  'Stripe Subscription id. Unique so renewals update the same membership row.';

comment on column public.memberships.last_invoice_id is
  'Last Stripe Invoice processed for status. Grant idempotency is the invoice-keyed purchase row.';

create unique index if not exists memberships_stripe_subscription_uidx
  on public.memberships (stripe_subscription_id);

create index if not exists memberships_user_id_idx
  on public.memberships (user_id);

create index if not exists memberships_stripe_customer_id_idx
  on public.memberships (stripe_customer_id);

create or replace function public.set_memberships_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_memberships_updated_at on public.memberships;
create trigger set_memberships_updated_at
  before update on public.memberships
  for each row
  execute function public.set_memberships_updated_at();

alter table public.memberships enable row level security;

drop policy if exists memberships_select_own on public.memberships;
create policy memberships_select_own
  on public.memberships
  for select
  to authenticated
  using (user_id = auth.uid());

revoke all on table public.memberships from public, anon, authenticated;
grant select on table public.memberships to authenticated;
grant all on table public.memberships to service_role;

do $$
declare
  memberships_id_sequence regclass;
begin
  memberships_id_sequence := pg_get_serial_sequence('public.memberships', 'id')::regclass;
  if memberships_id_sequence is not null then
    execute format(
      'revoke usage, select on sequence %s from authenticated, anon',
      memberships_id_sequence
    );
    execute format(
      'grant usage, select on sequence %s to service_role',
      memberships_id_sequence
    );
  end if;
end;
$$;

notify pgrst, 'reload schema';
