-- Welcome Advertising Image: once-per-user grant + 30-day network anti-abuse.
-- Privacy: persist only HMAC network keys — never raw IP.

-- 1) Once-per-user welcome grant uniqueness on ledger
create unique index if not exists entitlement_ledger_welcome_ai_grant_uidx
  on public.entitlement_ledger (user_id)
  where entry_type = 'grant'
    and entitlement_kind = 'advertising_asset'
    and product_id = 'welcome_advertising_image';

-- 2) Durable anti-abuse identity for FREE WELCOME only (hashed, not raw IP)
create table if not exists public.welcome_advertising_image_network_claims (
  id bigint generated by default as identity primary key,
  network_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  claimed_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint welcome_ai_network_claims_metadata_object_check
    check (jsonb_typeof(metadata) = 'object')
);

-- One welcome network claim row per user (lifetime once-per-user pairing).
create unique index if not exists welcome_ai_network_claims_user_uidx
  on public.welcome_advertising_image_network_claims (user_id);

create index if not exists welcome_ai_network_claims_network_claimed_idx
  on public.welcome_advertising_image_network_claims (network_key, claimed_at desc);

alter table public.welcome_advertising_image_network_claims enable row level security;

revoke all on table public.welcome_advertising_image_network_claims
  from public, anon, authenticated;
grant all on table public.welcome_advertising_image_network_claims to service_role;

do $$
declare
  claims_id_sequence regclass;
begin
  claims_id_sequence := pg_get_serial_sequence(
    'public.welcome_advertising_image_network_claims',
    'id'
  )::regclass;
  if claims_id_sequence is not null then
    execute format('grant usage, select on sequence %s to service_role', claims_id_sequence);
  end if;
end;
$$;

-- 3) Idempotent server grant RPC (amount fixed at 1; eligibility + network gate inside)
-- Default cooldown: 720 hours / 30 days.
create or replace function public.grant_welcome_advertising_image(
  p_user_id uuid,
  p_network_key text,
  p_cooldown_hours integer default 720,
  p_metadata jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
  v_already_user boolean;
  v_network_blocked boolean;
  v_cooldown_hours integer := greatest(coalesce(p_cooldown_hours, 720), 1);
begin
  if p_network_key is null or length(p_network_key) < 16 then
    raise exception 'invalid network_key';
  end if;

  -- Already granted to this user → idempotent success, no second credit
  select exists (
    select 1 from public.entitlement_ledger
    where user_id = p_user_id
      and entry_type = 'grant'
      and entitlement_kind = 'advertising_asset'
      and product_id = 'welcome_advertising_image'
  ) into v_already_user;

  if v_already_user then
    return jsonb_build_object(
      'granted', false,
      'reason', 'already_granted',
      'quantity', 0
    );
  end if;

  -- Shared-network recent claim by another user → account ok, no free grant
  select exists (
    select 1 from public.welcome_advertising_image_network_claims
    where network_key = p_network_key
      and user_id <> p_user_id
      and claimed_at > now() - make_interval(hours => v_cooldown_hours)
  ) into v_network_blocked;

  if v_network_blocked then
    return jsonb_build_object(
      'granted', false,
      'reason', 'network_ineligible',
      'quantity', 0
    );
  end if;

  insert into public.entitlement_balances (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  begin
    update public.entitlement_balances
    set advertising_assets_remaining = advertising_assets_remaining + 1
    where user_id = p_user_id
    returning advertising_assets_remaining into v_balance;

    insert into public.entitlement_ledger (
      user_id, entry_type, entitlement_kind, quantity, balance_after,
      product_id, metadata
    ) values (
      p_user_id, 'grant', 'advertising_asset', 1, v_balance,
      'welcome_advertising_image',
      coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('source', 'welcome_advertising_image')
    );

    insert into public.welcome_advertising_image_network_claims (
      network_key, user_id, metadata
    ) values (
      p_network_key, p_user_id, coalesce(p_metadata, '{}'::jsonb)
    )
    on conflict (user_id) do nothing;

    return jsonb_build_object(
      'granted', true,
      'reason', 'granted',
      'quantity', 1,
      'balance_after', v_balance
    );
  exception
    when unique_violation then
      return jsonb_build_object(
        'granted', false,
        'reason', 'already_granted',
        'quantity', 0
      );
  end;
end;
$$;

revoke all on function public.grant_welcome_advertising_image(uuid, text, integer, jsonb)
  from public, anon, authenticated;
grant execute on function public.grant_welcome_advertising_image(uuid, text, integer, jsonb)
  to service_role;

notify pgrst, 'reload schema';
