-- Sprint RC1.2: Recover purchases infrastructure for the live schema.
--
-- Live compatibility:
--   public.assets.id      bigint
--   auth.users.id         uuid
--   public.purchases      absent at audit time
--
-- Scope:
--   Create only public.purchases and its supporting purchase-specific
--   constraints, indexes, trigger, grants, and RLS policies.

create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_id bigint not null references public.assets(id) on delete cascade,
  product_id text not null,
  amount_mxn integer not null,
  currency text not null default 'MXN',
  status text not null default 'pending',
  provider text not null,
  provider_reference text,
  payment_method text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,

  constraint purchases_product_id_not_blank check (btrim(product_id) <> ''),
  constraint purchases_amount_mxn_positive check (amount_mxn > 0),
  constraint purchases_currency_iso_check check (currency = upper(currency) and length(currency) = 3),
  constraint purchases_status_check check (
    status in ('pending', 'awaiting_payment', 'completed', 'failed', 'cancelled')
  ),
  constraint purchases_provider_not_blank check (btrim(provider) <> ''),
  constraint purchases_payment_method_check check (
    payment_method is null
    or payment_method in ('card', 'oxxo', 'spei', 'wallet', 'other')
  ),
  constraint purchases_metadata_object_check check (jsonb_typeof(metadata) = 'object'),
  constraint purchases_completed_at_check check (
    status <> 'completed'
    or completed_at is not null
  )
);

create index if not exists purchases_user_id_idx
  on public.purchases(user_id);

create index if not exists purchases_asset_id_idx
  on public.purchases(asset_id);

create index if not exists purchases_status_idx
  on public.purchases(status);

create index if not exists purchases_created_at_idx
  on public.purchases(created_at desc);

create unique index if not exists purchases_provider_reference_uidx
  on public.purchases(provider, provider_reference)
  where provider_reference is not null;

create or replace function public.set_purchases_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_purchases_updated_at on public.purchases;
create trigger set_purchases_updated_at
  before update on public.purchases
  for each row
  execute function public.set_purchases_updated_at();

alter table if exists public.purchases enable row level security;

drop policy if exists "purchases_select_own" on public.purchases;
create policy "purchases_select_own"
  on public.purchases
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "purchases_insert_own" on public.purchases;
create policy "purchases_insert_own"
  on public.purchases
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "purchases_update_own" on public.purchases;
create policy "purchases_update_own"
  on public.purchases
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update on table public.purchases to authenticated;
grant all on table public.purchases to service_role;

do $$
declare
  purchases_id_sequence regclass;
begin
  purchases_id_sequence := pg_get_serial_sequence('public.purchases', 'id')::regclass;

  if purchases_id_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', purchases_id_sequence);
    execute format('grant usage, select on sequence %s to service_role', purchases_id_sequence);
  end if;
end;
$$;

notify pgrst, 'reload schema';
